from ckanext.configpermission import default_roles

from pylons import config

default_permissions = [{'display_name': 'Create Group', 'name': 'group_create', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Create Related Items', 'name': 'related_create', 'role': default_roles.REG_USER},
                       {'display_name': 'Show Package', 'name': 'package_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Package List + Resources', 'name': 'current_package_list_with_resources', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Resource', 'name': 'resource_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'File Upload', 'name': 'file_upload', 'role': default_roles.MEMBER},
                       {'display_name': 'Show Groups', 'name': 'group_list_authz', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Related', 'name': 'related_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Delete Revision History', 'name': 'revision_delete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Create Organization Member', 'name': 'organization_member_create', 'role': default_roles.ADMIN},
                       {'display_name': 'Delete Organization Member', 'name': 'member_delete', 'role': default_roles.ADMIN},
                       {'display_name': 'Show Organization Revision List', 'name': 'organization_revision_list', 'role': default_roles.REG_USER},
                       {'display_name': 'View Site', 'name': 'site_read', 'role': default_roles.ANON_USER},
                       {'display_name': 'Delete Group Member', 'name': 'group_member_delete', 'role': default_roles.ADMIN},
                       {'display_name': 'View User following list', 'name': 'user_followee_list', 'role': default_roles.REG_USER},
                       {'display_name': 'View Vocabulary List', 'name': 'vocabulary_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Request Password Reset', 'name': 'request_reset', 'role': default_roles.REG_USER},
                       {'display_name': 'Updated Item Related', 'name': 'related_update', 'role': default_roles.SYSADMIN},
                       {'display_name': 'View Organizations in Autocomplete', 'name': 'organization_autocomplete', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Group Revisions', 'name': 'group_revision_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Create New Group', 'name': 'group_create', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Set Resource Views', 'name': 'resource_create_default_resource_views', 'role': default_roles.ADMIN},
                       {'display_name': 'Delete Related Items', 'name': 'related_delete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Invite User to Group', 'name': 'user_invite', 'role': default_roles.ADMIN},
                       {'display_name': 'Change Package State', 'name': 'package_change_state', 'role': default_roles.EDITOR},
                       {'display_name': 'View Organization Follower List', 'name': 'organization_followee_list', 'role': default_roles.MEMBER},
                       {'display_name': 'View Dataset Follower List', 'name': 'dataset_followee_list', 'role': default_roles.MEMBER},
                       {'display_name': 'View Member Roles', 'name': 'member_roles_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Change Revision State', 'name': 'revision_change_state', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Show Revisions', 'name': 'revision_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Purge Dataset', 'name': 'dataset_purge', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Autocomplete Group Names', 'name': 'group_autocomplete', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Revisions Package', 'name': 'package_revision_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Patch Resource', 'name': 'resource_patch', 'role': default_roles.EDITOR},
                       {'display_name': 'Delete User', 'name': 'user_delete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Create Resource', 'name': 'resource_create', 'role': default_roles.MEMBER},
                       {'display_name': 'Restore Revisions', 'name': 'revision_undelete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Remove Resource View', 'name': 'resource_view_delete', 'role': default_roles.EDITOR},
                       {'display_name': 'View New Activities Count in Dashboard', 'name': 'dashboard_new_activities_count', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Full Package', 'name': 'package_show_rest', 'role': default_roles.REG_USER},
                       {'display_name': 'Show Resource Status', 'name': 'resource_status_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Patch Group', 'name': 'group_patch', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Show all Groups', 'name': 'group_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show runtime-editable configuration option', 'name': 'config_option_show', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Autocomplete Package Name', 'name': 'package_autocomplete', 'role': default_roles.MEMBER},
                       {'display_name': 'Change Group State', 'name': 'group_change_state', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Add Resource View', 'name': 'resource_view_create', 'role': default_roles.MEMBER},
                       {'display_name': 'Update Organization', 'name': 'organization_update', 'role': default_roles.ADMIN},
                       {'display_name': 'Create Vocabulary', 'name': 'vocabulary_create', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Update User', 'name': 'user_update', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Purge Organization', 'name': 'organization_purge', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Update Package', 'name': 'package_update', 'role': default_roles.EDITOR},
                       {'display_name': 'Show All Tags', 'name': 'tag_show_rest', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show All Followers Group', 'name': 'group_follower_list', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Update Term Translations', 'name': 'term_translation_update', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Format Autocomplete', 'name': 'format_autocomplete', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Tags', 'name': 'tag_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Group', 'name': 'group_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'List all Groups', 'name': 'group_list_available', 'role': default_roles.ANON_USER},
                       {'display_name': 'Clear Resource View', 'name': 'resource_view_clear', 'role': default_roles.ADMIN},
                       {'display_name': 'Delete Package Relationship', 'name': 'package_relationship_delete', 'role': default_roles.ADMIN},
                       {'display_name': 'Show all Revisions', 'name': 'revision_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Mark activities on Dashboard as old', 'name': 'dashboard_mark_activities_old', 'role': default_roles.REG_USER},
                       {'display_name': 'Show Organization', 'name': 'organization_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Update Group via REST', 'name': 'group_update_rest', 'role': default_roles.ADMIN},
                       {'display_name': 'Show Vocabulary', 'name': 'vocabulary_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'List runtime-editable configuration options', 'name': 'config_option_list', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Purge Group', 'name': 'group_purge', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Reorder resources against datasets', 'name': 'package_resource_reorder', 'role': default_roles.ANON_USER},
                       {'display_name': 'Bulk update Resources', 'name': 'bulk_update_public', 'role': default_roles.EDITOR},
                       {'display_name': 'Show all Tags', 'name': 'tag_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Delete Resource', 'name': 'resource_delete', 'role': default_roles.EDITOR},
                       {'display_name': 'Return the list of users that are following the given user', 'name': 'user_follower_list', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Update the runtime-editable configuration options', 'name': 'config_option_update', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Delete Vocabulary', 'name': 'vocabulary_delete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'View Package Relationships', 'name': 'package_relationships_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Package create Resource View', 'name': 'package_create_default_resource_views', 'role': default_roles.EDITOR},
                       {'display_name': 'Patch Package', 'name': 'package_patch', 'role': default_roles.EDITOR},
                       {'display_name': 'Create Vocabulary Tag', 'name': 'tag_create', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Show the list of users following the given Dataset', 'name': 'dataset_follower_list', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Tag Autocomplete', 'name': 'tag_autocomplete', 'role': default_roles.ANON_USER},
                       {'display_name': 'Reorder Resource View', 'name': 'resource_view_reorder', 'role': default_roles.EDITOR},
                       {'display_name': 'Get Site User', 'name': 'get_site_user', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Delete Task Status', 'name': 'task_status_delete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Delete Package', 'name': 'package_delete', 'role': default_roles.ADMIN},
                       {'display_name': 'Reset User password', 'name': 'user_reset', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Send Emailt notifications', 'name': 'send_email_notifications', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Update Vocabulary', 'name': 'vocabulary_update', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Show License List', 'name': 'license_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Delete Group', 'name': 'group_delete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Show task status', 'name': 'task_status_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Bulk update to Private', 'name': 'bulk_update_private', 'role': default_roles.EDITOR},
                       {'display_name': 'Rate a dataset', 'name': 'rating_create', 'role': default_roles.REG_USER},
                       {'display_name': 'Return List of Organizations User can edit', 'name': 'organization_list_for_user', 'role': default_roles.ANON_USER},
                       {'display_name': 'Create/Approve Membership', 'name': 'member_create', 'role': default_roles.ADMIN},
                       {'display_name': 'Show User info', 'name': 'user_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Update a relationship between two datasets', 'name': 'package_relationship_update', 'role': default_roles.EDITOR},
                       {'display_name': 'Make User a member of a Group', 'name': 'group_member_create', 'role': default_roles.ADMIN},
                       {'display_name': 'Update Resource View', 'name': 'resource_view_update', 'role': default_roles.EDITOR},
                       {'display_name': "Cycle a user's API key", 'name': 'user_generate_apikey', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Edit Group permissions', 'name': 'group_edit_permissions', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Search Package', 'name': 'package_search', 'role': default_roles.ANON_USER},
                       {'display_name': 'Delete Tag', 'name': 'tag_delete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Update Package Owner Org', 'name': 'package_owner_org_update', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Create Package Relationship', 'name': 'package_relationship_create', 'role': default_roles.EDITOR},
                       {'display_name': 'Show Resource View', 'name': 'resource_view_show', 'role': default_roles.REG_USER},
                       {'display_name': 'Delete Organization', 'name': 'organization_delete', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Bulk Delete', 'name': 'bulk_update_delete', 'role': default_roles.ADMIN},
                       {'display_name': 'Create Package via REST', 'name': 'package_create_rest', 'role': default_roles.REG_USER},
                       {'display_name': 'Patch Organization', 'name': 'organization_patch', 'role': default_roles.ADMIN},
                       {'display_name': 'List Organizations', 'name': 'organization_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Remove Organization Member', 'name': 'organization_member_delete', 'role': default_roles.ADMIN},
                       {'display_name': 'Update Group', 'name': 'group_update', 'role': default_roles.ADMIN},
                       {'display_name': 'Show Packages list', 'name': 'package_list', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Group via REST', 'name': 'group_show_rest', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show Dashboard Activity List', 'name': 'dashboard_activity_list', 'role': default_roles.REG_USER},
                       {'display_name': 'Show all Resource Views for a Resource', 'name': 'resource_view_list', 'role': default_roles.REG_USER},
                       {'display_name': 'Return the help string for a particular API action', 'name': 'help_show', 'role': default_roles.ANON_USER},
                       {'display_name': 'Create new User', 'name': 'user_create', 'role': default_roles.ANON_USER},
                       {'display_name': 'Update Resource', 'name': 'resource_update', 'role': default_roles.EDITOR},
                       {'display_name': 'Autocomplete usernames', 'name': 'user_autocomplete', 'role': default_roles.ANON_USER},
                       {'display_name': 'Show the list of users following the given Organization', 'name': 'organization_follower_list', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Create Group via REST', 'name': 'group_create_rest', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Create Package', 'name': 'package_create', 'role': default_roles.MEMBER},
                       {'display_name': 'Update Task status', 'name': 'task_status_update', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Return the list of objects that are followed by the given user.', 'name': 'followee_list', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Create a new activity stream activity', 'name': 'activity_create', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Update Package via REST', 'name': 'package_update_rest', 'role': default_roles.EDITOR},
                       {'display_name': 'Create Organization', 'name': 'organization_create', 'role': default_roles.SYSADMIN},
                       {'display_name': 'Show all users', 'name': 'user_list', 'role': default_roles.REG_USER},
                       ]

selected_permissions = config.get('ckan.configpermission.permissions', '*').strip()
# * means we want to select all permissions
if selected_permissions == '*':
    selected_permissions = [x['name'] for x in default_permissions]
else:
    # Turn comma separated string into a proper python list.
    selected_permissions = [x.strip() for x in selected_permissions.split(' ')]
# Get the permissions we selected.
permissions = [x for x in default_permissions if x['name'] in selected_permissions]